### ISSUE TITLE
Reload extension if settings change

### ISSUE THREAD

**Issue by PanAeon** [PanAeon/vscode-dhall-lsp-server#1]

**Comment by EggBaconAndSpam** [comment]
I think it would be better to handle settings on the server side, thus minimising the amount of VSCode specific client-side logic. See [didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration).

**Comment by EggBaconAndSpam** [comment]
> I think it would be better to handle settings on the server side, thus minimising the amount of VSCode specific client-side logic. See [didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration).

I'm adding functionality along those lines to the server now. I don't think this issue is still relevant.
