### ISSUE TITLE
Handle dhall-lsp-server crash

### ISSUE THREAD

**Issue by PanAeon** [PanAeon/vscode-dhall-lsp-server#2]
Server should be restarted on crash. Extra points if extension can remember number of times the server has crashed, stops restarting it after some threshold and displays a meaningful user message.

**Comment by EggBaconAndSpam** [comment]
This is already handled by VSCode's lsp implementation. This is implicitely mentioned in [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node/blob/da32641d40369e6b662643546a80c7b508416ce0/README.md):

### 3.5.0 Server and Client

* allow the client to start the server in detached mode. If the server is running detached the client will not monitor the server process and kill it on shutdown.
* bug fixing.
